title: OpenSBPM
author:
  name: Stefan Sedelmaier
  email: 'stefan@sedelmaier.at'
metadata:
    description: 'OpenSBPM is easy to use, yet powerful, open source subjectoriented business process model workflow engine'

