title: OpenSBPM
author:
  name: Stefan Sedelmaimer
  email: 'stefan@sedelmaier.at'
metadata:
    description: 'OpenSBPM ist easy to use, yet powerful, open source subjectoriented business process model workflow engine'

